name: guides
channels:
  - conda-forge
  - nodefaults
dependencies:
  - ghp-import=2.1.0
  - jupytext=1.16.0
  - linkify-it-py=2.0.3
  - myst-nb=1.1.1
  - nb-clean=3.3.0
  - pydata-sphinx-theme=0.15.4
  - pygit2=1.15.1
  - python-frontmatter=1.1.0
  - python=3.10.14
  - r-base=4.1.3
  - r-irkernel=1.3.2
  - sphinx-autobuild=2024.4.16
  - sphinx-copybutton=0.5.2
  - sphinx-design=0.5.0
  - sphinx-external-toc=1.0.1
  - sphinx-notfound-page=1.0.0
  - sphinx-togglebutton=0.3.2
  - sphinx=7.4.7
